### ISSUE TITLE
l'import du thesaurus s'est mal passé mais le logiciel dit "parfait" 

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#10]
C'est assez normal que l'import de thésausrus se soit mal passé - c’est un fichier owl dont j'ai changé le nom - c'est une sortie du logiciel thesauform que l'on utilise au CEFE http://t-sita.cefe.cnrs.fr/t-sita/index - mais c'est pas trop normal qu'opentheso soit content de son importation vu le résultat

![image](https://user-images.githubusercontent.com/29607993/64178036-f3901880-ce60-11e9-8c34-b4b57c593a03.png)

**Comment by miledrousset** [comment]
Disons que le logiciel essaie de reconnaitre les balises de type SKOS, s'il en trouve, il se contente de les récupérer et proposer un résultat, s'il l'utilisateur n'est pas satisfait, il supprime, corrige et recommence ;)
Opentheso indique une erreur quand c'est majeur, ca laisse la possibilité à l'utilisateur de faire des corrections et ajustements après l'import. Il y a toute une série des corrections automatiques intégrées au logiciel, on arrive souvent à reconstruire un thésaurus mal formé au départ.
Envoie moi une copie du thésaurus, je peux l'analyser pour mieux comprendre ce qui se passe.
