### ISSUE TITLE
importation -> reinialisation des parametres

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#11]
Après avoir envoyé mon fichier à traiter je m'aperçois que ce n'est pas le bon.  Malheureusement je n'ai plus accès à vider la sélection. Si je sors et rerentre dans la commande importer il me montre toujours mon "mauvais" fichier. ET si je finis par faire importer il ne m'importe rien. 
![image](https://user-images.githubusercontent.com/29607993/64270764-5dc9bb80-cf3c-11e9-836a-5b7a2c1e3c3f.png)

**Comment by miledrousset** [comment]
Ok, j'ai vu, il manque un bouton pour vider le cache, je note pour correction, merci.
Sinon, il suffit de cliquer sur l'onglet (Edition), tout sera initialisé.
