### ISSUE TITLE
import csv et termes associés

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#12]

**Comment by quidoz** [comment]
Bonjour
Suite à une importation d'un fichier csv, je découvre sous opentheso que j'ai des termes associés pour microhabitat quand il n'y a pas de marqué dans le fichier csv. Il a déduit cela d'où ?
[data-tsita_opentheso.TXT](https://github.com/miledrousset/opentheso/files/3681397/data-tsita_opentheso.TXT)


![image](https://user-images.githubusercontent.com/29607993/66049448-b1bfc400-e52b-11e9-9cad-f77e107b46e3.png)

**Comment by miledrousset** [comment]
Ce n'est pas un bug mais plutôt une information qui vient de ton fichier CSV : 
exp : Soil (id: 235) a comme RT (terme associé) Microhabitat (id:231)
c'est le même cas pour les autres (Litter, Living_tree ....)
comme cette relation est réciproque, alors c'est normal qu'elle existe.
