### ISSUE TITLE
recherche bizarre

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#13]
Bonjour
Je n'arrive pas à reproduire le phénomène chaque fois, mais il semble que la première fois que je fais une recherche  avec la case "index" en haut à gauche, il fait la recherche dans le thésaurus en français bien que je lui ai indiqué en haut à gauche que mon thesaurus était en anglais. Dans l'exemple ci dessous j'ai cherché microhabitat

![image](https://user-images.githubusercontent.com/29607993/66049927-90aba300-e52c-11e9-9f08-94bc84e7dd72.png)

**Comment by miledrousset** [comment]
Bonjour,
Effectivement, c'est un bug que j'ai pu reproduire, c'est corrigé, ca sera pour la prochaine mise à jour.
Merci
