### ISSUE TITLE
groupes -> des utilisateurs + thesaurus

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#14]
Comment fait on pour détruire des groupes que l'on a créé par mégarde ? comment les renommer ? Est ce obligatoire de créer des groupes ?

**Comment by miledrousset** [comment]
On peut facilement supprimer ou modifier un groupe (voir copie d'écran).
La version 5 d'Opentheso va intégrer une nouvelle gestion des groupes/collections, il n'y aura alors plus d'obligation de créer un groupe pour pouvoir créer des concepts.

<img width="860" alt="Capture d’écran 2019-10-21 à 09 39 50" src="https://user-images.githubusercontent.com/3404662/67185844-077ae400-f3e7-11e9-97b8-218509c4f446.png">

**Comment by quidoz** [comment]
Bonjour

Je parlais de ce groupe la 

A+

MCQ

**Comment by miledrousset** [comment]
Quel groupe ? je ne comprend pas ?

**Comment by quidoz** [comment]
Bonjour

 

J’ai fait des groupes pour mettre des thesaurus et des utilisateurs. J’ai fait stage1 à stage5, j’ai fait aussi ttt (regardes sur mon instance http://opentheso6.mom.fr/opentheso6/profiles.xhtml)

 

A+

 

MCQ

 

 

+++++++++++++++++

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie

 

 

De : Rousset Miled [mailto:notifications@github.com] 
Envoyé : lundi 21 octobre 2019 14:37
À : miledrousset/opentheso <opentheso@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [miledrousset/opentheso] groupes -> des utilisateurs + thesaurus (#14)

 

Quel groupe ? je ne comprend pas ?

**Comment by miledrousset** [comment]
Ah Ok, tu parles du module de gestion de profils ! 
Effectivement, je n'ai pas prévu de modifier un groupe / projet ni supprimer, je vais ajouter cela à la liste des taches.
Pour supprimer un groupe/projet, je peux le faire manuellement en attendant.
Merci

**Comment by quidoz** [comment]
Bonjour

 

OK est ce que tu peux les supprimer tous ?


A+


MCQ

**Comment by miledrousset** [comment]
C'est fait.
