### ISSUE TITLE
Ajout de terme générique

### ISSUE THREAD

**Issue by cmasset** [miledrousset/opentheso_archive#15]
Bonjour,
Est-il normal que le menu d'ajout de terme générique n'apparaisse que si on a déjà un terme générique ? Ne devrait-on pas pouvoir en ajouter pour un top-terme ?
Merci,
Cyril Masset.

**Comment by miledrousset** [comment]
Bonjour,
Vous pouvez faire l'action par plusieurs méthodes : 
- drag and drop du Top terme vers le concept que vous souhaitez
- couper / coller (même action)
- ajouter une relation (terme spécifique) au concept cible

Si malgré tout ceci ne répond pas à vos besoins, je pourrais remettre cette action (qui était possible dans une ancienne version).
Cordialement
Miled Rousset

**Comment by cmasset** [comment]
Merci pour votre réponse c'est parfait !
Cordialement,
Cyril Masset.
