### ISSUE TITLE
acces a la documentation utilisateur

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#2]
Bonjour

Je n'arrive pas à lire le fichier guide d'utilisateur.pdf

MCQ

**Comment by miledrousset** [comment]
Bonjour,
Avez-vous essayé par ce lien qui est dans la partie Wiki 
https://github.com/miledrousset/opentheso/blob/master/src/main/resources/install/Manuel%20d%E2%80%99utilisateur%20Opentheso_V4.pdf
Miled

**Comment by quidoz** [comment]
Bonjour

Merci pour le message. J’avais fini par trouver un lien qui marchait

Je profite de ce message pour vous poser une question : est-ce que vous avez une installation « bac à sable » que je pourrais utiliser pour tester votre logiciel ?

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : Rousset Miled [mailto:notifications@github.com]
Envoyé : mercredi 19 juillet 2017 14:49
À : miledrousset/opentheso <opentheso@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [miledrousset/opentheso] acces a la documentation utilisateur (#2)


Bonjour,
Avez-vous essayé par ce lien qui est dans la partie Wiki 👍 https://github.com/miledrousset/opentheso/blob/master/src/main/resources/install/Manuel%20d%E2%80%99utilisateur%20Opentheso_V4.pdf
Miled

**Comment by miledrousset** [comment]
Oui, j'ai un serveur Bac à sable, il est à cette adresse 
http://opentheso3.mom.fr/
user = demo1
pass = demo1
N'hésitez pas à me poser des questions, j'ai tardé à répondre parce que le service d'alertes était désactivé.
Miled

**Comment by quidoz** [comment]
Bonjour

Est-ce que je pourrais envoyer cette adresse à mes collègues du GDR SémanDiv pour qu’ils puissent aussi tester le logiciel ?

rép : Oui bien sûr, c'est fait pour. 

On est en train de regarder quelques produits pour voir s’il est « intelligent » de poursuivre le développement de notre produit https://github.com/CESAB-FRB/Thesauform . Dans le test, on a pensé à OpenTheso dont tout le monde nous dit du bien, de Vocbench qui est très connu et de TemaTres (dont je ne sais plus pourquoi il a été mis sur la liste)

rép : Je suis content que le logiciel réponde aux attentes des utilisateurs, c'est le but.

Nous recherchons un outil

-          qui est simple d’utilisation pour un non spécialiste du monde terminologique

-          qui permet aux experts de participer à la définition des termes et de voter pour la définition qui leur semble la meilleure (cf en dessous notre procédure de vote).

rép : Dans Opentheso, il y a un module de gestion de candidats, il permet à plusieurs personnes de discuter sur un concept (avec commentaires et archives) puis il a un système d'alerte pour prévenir des nombres de propositions sur ce candidat. Une fois le candidat est approuvé, il peut être intégrer dans le thésaurus (en conservant une archive des discussions).
Bonne vacances et n'hésitez pas à revenir vers moi pour d'autres questions. 
  

Votre outil remplit la condition 1 mais je n’ai pas trouvé d’infos pour savoir si elle remplit la condition 2.

C’était un bref aperçu de nos besoins. Je pars en vacances ce soir jusqu’au 20 Aout.

A+

MCQ



[cid:image001.png@01D300B9.8175FF20]



+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : Rousset Miled [mailto:notifications@github.com]
Envoyé : mercredi 19 juillet 2017 17:46
À : miledrousset/opentheso <opentheso@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [miledrousset/opentheso] acces a la documentation utilisateur (#2)


Oui, j'ai un serveur Bac à sable, il est à cette adresse
http://opentheso3.mom.fr/
user = demo1
pass = demo1
N'hésitez pas à me poser des questions, j'ai tardé à répondre parce que le service d'alertes était désactivé.
Miled
