### ISSUE TITLE
installation  de la version 4.3.6

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#4]
J'ai quelques remarques suite à l'installation de la version 4.3.6 sur debian 9. J'ai suivi la doc du mardi 13 juin 2017. L'installation fonctionne mais je tenais à signaler quelques éléments manquants ou difficile de la doc.
- la partie en jaune "modifier les chemins de conf" n'est pas très clair
- je n'ai pas fait le parametrage de tomcat8 (page 4) car je ne sais pas à quel niveau il faut mettre la ligne dans /etc/init.d/tomcat8
- il n'existe pas de preferences_dist.properties et hikari_dist.properties dans la version installée
- le fichier "preferences.properties" contient très peu de choses. ca serait bien d'en faire sur *.war plus développé

**Comment by miledrousset** [comment]
Merci pour vos remarques, 
Je vais revoir la doc en suivant une installation complète, je vais corriger aussi les fichiers manquants dans le war.
Ca sera visible dans la prochaine version.
Merci pour votre confiance.
