### ISSUE TITLE
insertion d'une image

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#5]
J"'ai un message d'erreur java quand je tente une insertion d'image. J'ai l'impression de tout avoir bien configuré

01-Mar-2018 19:31:09.675 GRAVE [http-nio-8080-exec-9] mom.trd.opentheso.SelectedBeans.FileBean.chargeImage null
 java.io.FileNotFoundException: /var/data/html/images/http:/www.termsciences.fr/vocabs/Biodiversite/398 01-03-2018 19-31-09.jpg (Aucun fichier ou dossier de ce type)

**Comment by miledrousset** [comment]
Bonjour,
Tout d'abord, désolé pour le retard de la réponse, mes alertes passaient dans les SPAMS !!
Pour configurer un chemin de dépôt pour les images, il ne faut pas mettre l'URL complète, voici un exemple : /data/opentheso/images/
pour stocker des images dans le dossier sur le serveur.
Je travailles actuellement sur la possibilité d'ajouter des URL pour des images distantes (ca sera pour la prochaine version).

**Comment by quidoz** [comment]
J'ai bien mis /var/data/html/images dans le module admin preference images et mis resize dans le dossier resize. J'obtiens le message suivant
[copie-ecran.pdf](https://github.com/miledrousset/opentheso/files/1813109/copie-ecran.pdf)

**Comment by miledrousset** [comment]
ecrivez moi en privé, je vous donne accès à mon serveur bac à sable, ca vous permet de comparer 
miled(.)rousset(@)mom(.)fr
