### ISSUE TITLE
gestion des candidats

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#6]
J'ai du mal avec ce module. Je ne comprend pas sa logique et donc dans quel cas on peut l'utiliser.
On peut ajouter me semble t'il uniquement un nom de descripteur, pas sa définition, ni les termes voisins, ...

**Comment by miledrousset** [comment]
Le module "Candidats" sert à proposer des les termes qu'on souhaite intégrer dans le thésaurus, il peut y avoir plusieurs personnes qui sont intéressées par le même terme, donc, il peut y avoir une discussion, commentaires, proposition de niveau etc... toujours autour de ce même terme.
A la fin, les admins du thésaurus peuvent accepter d'intégrer le terme ou le refuser.
C'est un mode de travail qui convient à un réseau d'utilisateurs pour un même thésaurus.

**Comment by quidoz** [comment]
J'ai trouvé une vidéo qui explique cela https://www.youtube.com/channel/UCCuY3Jf8KXWMlMVZkdADH1g

SI je comprend bien une fois un terme "publié", si on veut ajouter une définition dans une autre langue, on ne passe pas par le module "candidats". C'est accepté par défaut

**Comment by miledrousset** [comment]
C'est exacte, une fois que le candidat est inséré dans le thésaurus, la gestion de ce concept ne passe plus par le module candidat.
