### ISSUE TITLE
a la recherche de documentation sur le module BDD

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#7]
tout est dans le titre ...

**Comment by miledrousset** [comment]
Je ne comprend pas ce que vous souhaitez ? 
- une doc sur les requêtes SQL côté application ?
- une donc sur la base de données SQL brute ?
- vous souhaitez rajouter d'autres tables SQL ? ou d'autres fonctionnalités ?

**Comment by quidoz** [comment]
En parcourant votre logiciel, je suis tombée sur une icone grisé "options BDD" dans le module Edition. Je me demandai ce qu'il avait derrière. Je pense que l'icone grisé vient du fait que je n'ai pas mis oui dans le module admin préférences BDD. J'avoue ne pas comprendre à quoi correspond les paramètres de ce module admin préférence BDD

**Comment by miledrousset** [comment]
Ce paramètre sert à interconnecter les concepts d'un thésaurus à une base de données distante (ici vous paramétrez l'URL de connexion (type REST, mysql, ...)
J'ai des exemples si ca vous intéresse ce mode de fonctionnement !

**Comment by quidoz** [comment]
C'est exactement ce que l' on veut dans le GDR semandiv. Je veux bien des exemples

**Comment by miledrousset** [comment]
Voici une copie d'écran pour expliquer le paramétrage à mettre en place. 

![capture d ecran 2018-03-15 a 10 01 37](https://user-images.githubusercontent.com/3404662/37453584-6562bda8-2838-11e8-8de7-97b796a2b518.png)

**Comment by quidoz** [comment]
Bonjour

Dans ce message vous me proposiez des exemples pour m’expliquer ce module. J’en veux bien

A+

MCQ



+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : Rousset Miled [mailto:notifications@github.com]
Envoyé : jeudi 15 mars 2018 08:55
À : miledrousset/opentheso <opentheso@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [miledrousset/opentheso] a la recherche de documentation sur le module BDD (#7)


Ce paramètre sert à interconnecter les concepts d'un thésaurus à une base de données distante (ici vous paramétrez l'URL de connexion (type REST, mysql, ...)
J'ai des exemples si ca vous intéresse ce mode de fonctionnement !

**Comment by miledrousset** [comment]
Bonjour,
La problématique est assez simple à régler, il suffit d'avoir 2 URL type REST pour accéder à votre BDD :
- une pour lier le concept à votre base de données
exp : il faut rentrer ceci en paramètre : (https://www.votreSite.fr/concept/##value##) 
         ##value## correspond à une variable qui prend la valeur du concept en cours
         ensuite, quand vous cliquez sur le concept (qui a un  id = 225), ca vous donne un lien pour accéder aux références de votre BDD (https://www.votreSite.fr/concept/225)
PS: l'accès peut se faire par ID du concept ou par valeur suivant le paramètre que vous définissez.

- une pour le total de résultat
exp : https://www.votreSite.fr/concept/##conceptId##/total 
       ensuite, quand vous cliquez sur le concept, vous avez en temps réel le total des notices ou références dans la BDD  (https://www.votreSite.fr/concept/225/total)

Voilà, j'espère que c'est un peu plus clair.
voici une URL sur projet qui l'utilise : 
http://pactols.frantiq.fr
M.R.
