### ISSUE TITLE
export en skos d'un  terme

### ISSUE THREAD

**Issue by quidoz** [miledrousset/opentheso_archive#8]
Je suis étonnée que les exports des termes cachés ne soient pas tagués "hiddenlabel" quand je fais un export d'un terme. Ils sont tagués altlabel comme les termes synonymes non cachées

**Comment by miledrousset** [comment]
Effectivement, quand on exporte le concept à la volé (interface public), il n'y a pas cette info;
mais en export normal, l'information est présente.
Je vais corriger.
Merci
