### ISSUE TITLE
Import des termes associés (related) en Skos

### ISSUE THREAD

**Issue by cmasset** [miledrousset/opentheso_archive#9]
Bonjour,
Il semble qu'il y ait un souci d'import des termes associés dans l'import Skos. En effet, même pour l'exemple "geo.skos.xml", les "skos:related" semblent totalement ignorés et aucun terme associé n'est créé.

Merci et bravo pour ce projet !

**Comment by miledrousset** [comment]
Bonjour,
Merci pour ce signalement, il y a effectivement un bug au moment de l'import des relations associées (RT), je l'ai corrigé, c'est dans la version 4.5.1 que je viens de déposer en release.
Merci aussi pour vos encouragements.
Cordialement

**Comment by cmasset** [comment]
Merci beaucoup et bravo pour votre réactivité !
